### ISSUE TITLE
Auto refresh is not working while updating the data in the forms.

### ISSUE THREAD

**Issue by ajay021987** [Devnawjesh/hr-payroll#1]
After submit the data it not auto-refresh to shows updated data, we need to manually refresh the page than it shows the updated data.

**Comment by Devnawjesh** [comment]
please go to the view/footer.php and change the reload time 300000 to 3000 .
or change the ajax success response
`success: function(response) {
                                    $(".message").fadeIn('fast').delay(3000).fadeOut('fast').html(response);
                                    $('form').trigger("reset");
                                    window.setTimeout(function() {
                                        location.reload()
                                    }, 3000);
                                },`
