### ISSUE TITLE
How to use addbulk attendance

### ISSUE THREAD

**Issue by rakhmadtri** [Devnawjesh/hr-payroll#11]
How to use addbulk attendance, give me a csv format...

**Comment by Devnawjesh** [comment]
Please check this directory:
https://github.com/Devnawjesh/hr-payroll/blob/master/assets/images/data.csv

**Comment by rakhmadtri** [comment]
i was try import that file. still failure

**Comment by rakhmadtri** [comment]
![image](https://user-images.githubusercontent.com/14133910/71239420-19bac500-2339-11ea-8bed-80b0d86946e1.png)

**Comment by rakhmadtri** [comment]
give me solution brother...

**Comment by Devnawjesh** [comment]
sorry ,previous csv format was not correct.Note: Where Employee No will be the em_code on employee table.work duration,overtime will be the number of minutes who works.this system will convert to hours that helps you to generate salary dynamically. checkout this file 
https://github.com/Devnawjesh/hr-payroll/blob/master/assets/images/data.csv
