### ISSUE TITLE
How do you change password, I can't find any way to do it

### ISSUE THREAD

**Issue by Naji102** [Devnawjesh/hr-payroll#12]
title and 

2nd issue, In super admin panel, Red dot never goes away form notifications area.

![vibrant-colorful-gradients-swatches-set_1017-17663](https://user-images.githubusercontent.com/59081659/71239253-e6bc0580-2327-11ea-9b2d-c07c89f7cdcb.jpg)

**Comment by Devnawjesh** [comment]
1st issuse :go to my profile and where has a tab name Change Password on the right corner.
![danger 2](https://user-images.githubusercontent.com/39015159/71419536-19ecf480-269a-11ea-8139-ed90381ac9af.png)
![danger](https://user-images.githubusercontent.com/39015159/71419537-19ecf480-269a-11ea-8d2c-f8a7c0e8baba.png)
2nd Issue: Actually this heart beat icon has no functionality.If you want to reamove this icon just remove heart beat icon form header.php
![code](https://user-images.githubusercontent.com/39015159/71419608-7cde8b80-269a-11ea-9f29-0566cb026590.PNG)

Thanks
