### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by pavankumartg** [Devnawjesh/hr-payroll#2]
Doesn't login with the given credentials, the page refreshes but doesn't move further.

**Comment by Devnawjesh** [comment]
please update the database from database/genhr.sql . and login with
super admin
username : nawjeshbd@gmail.com password: 01723177901
admin:
username: admin@gmail.com password: admin123456
employee:
username: employee@gmail.com password: admin123456

**Comment by rakhmadtri** [comment]
edit button doesn't work when click on the second page.
