### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by garlicrats19** [Devnawjesh/hr-payroll#3]
Can't log-in, after I enter the credentials provided it just redirects me to http://localhost/hr-payroll-master/login, I used to be able to log-in using the credentials provided, I don't know now why I can't.

@Devnawjesh

**Comment by Devnawjesh** [comment]
please update the database from database/genhr.sql . and login with 
super admin
username : nawjeshbd@gmail.com password: 01723177901
admin:
username: admin@gmail.com password: admin123456
employee:
username: employee@gmail.com password: admin123456
