### ISSUE TITLE
internal server error 

### ISSUE THREAD

**Issue by Ra0ne** [Devnawjesh/hr-payroll#4]
Hey Devnawjesh,

I am new at coding can please help me out to run this project.
I tried to run it but getting an internal server error. I did copy-paste code into xampp htdocs and change apache httpd.conf htdocs /foldername .
please help me out step by step installation.

thankyou

**Comment by Devnawjesh** [comment]
Hey RaOne,

please clone this code into **htdocs** folder or download this code. after downloading please upzip the folder and paste the unzip folder to the htdocs folder then start your **apache and mysql** engine from xammp .after starting your apache and mysql engine go to **phpmyadmin** then create a database name genhr and import sql file from **database/genhr.sql** . then check your browser . hope everything will work fine.

best of luck

**Comment by Ra0ne** [comment]
Hey @Devnawjesh,

Thanks, it's working.
But when I change email id and password of (super admin, admin or employee) it won't log in. 

Thank you
